// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: coordination/v1/coordination.proto

package coordinationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinationService_RegisterDevice_FullMethodName        = "/nexusvpn.coordination.v1.CoordinationService/RegisterDevice"
	CoordinationService_Heartbeat_FullMethodName             = "/nexusvpn.coordination.v1.CoordinationService/Heartbeat"
	CoordinationService_StreamPeerUpdates_FullMethodName     = "/nexusvpn.coordination.v1.CoordinationService/StreamPeerUpdates"
	CoordinationService_ExchangeICECandidates_FullMethodName = "/nexusvpn.coordination.v1.CoordinationService/ExchangeICECandidates"
	CoordinationService_RequestRelay_FullMethodName          = "/nexusvpn.coordination.v1.CoordinationService/RequestRelay"
)

// CoordinationServiceClient is the client API for CoordinationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoordinationService is the control-plane gRPC API used by the NexusVPN
// client agent to register itself, discover peers on its networks, exchange
// ICE/NAT information for hole punching, and request relay allocation when
// direct peer-to-peer connectivity is not possible.
type CoordinationServiceClient interface {
	// RegisterDevice authenticates a device (via its device key + JWT) and
	// returns its assigned virtual IP and current network topology.
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	// Heartbeat reports liveness, NAT/endpoint info, and traffic counters.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// StreamPeerUpdates is a server-streaming RPC that pushes peer topology
	// changes (joins, leaves, endpoint changes) for all networks the device
	// belongs to, so the client can keep its local WireGuard peer table live.
	StreamPeerUpdates(ctx context.Context, in *StreamPeerUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerUpdate], error)
	// ExchangeICECandidates relays STUN-discovered candidate endpoints between
	// two peers to negotiate the best path (direct vs relay) for UDP hole punching.
	ExchangeICECandidates(ctx context.Context, in *ICEExchangeRequest, opts ...grpc.CallOption) (*ICEExchangeResponse, error)
	// RequestRelay asks the control plane for the least-loaded relay server
	// to fall back to when direct P2P connectivity cannot be established.
	RequestRelay(ctx context.Context, in *RequestRelayRequest, opts ...grpc.CallOption) (*RequestRelayResponse, error)
}

type coordinationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinationServiceClient(cc grpc.ClientConnInterface) CoordinationServiceClient {
	return &coordinationServiceClient{cc}
}

func (c *coordinationServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, CoordinationService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CoordinationService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) StreamPeerUpdates(ctx context.Context, in *StreamPeerUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinationService_ServiceDesc.Streams[0], CoordinationService_StreamPeerUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPeerUpdatesRequest, PeerUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinationService_StreamPeerUpdatesClient = grpc.ServerStreamingClient[PeerUpdate]

func (c *coordinationServiceClient) ExchangeICECandidates(ctx context.Context, in *ICEExchangeRequest, opts ...grpc.CallOption) (*ICEExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ICEExchangeResponse)
	err := c.cc.Invoke(ctx, CoordinationService_ExchangeICECandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) RequestRelay(ctx context.Context, in *RequestRelayRequest, opts ...grpc.CallOption) (*RequestRelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestRelayResponse)
	err := c.cc.Invoke(ctx, CoordinationService_RequestRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinationServiceServer is the server API for CoordinationService service.
// All implementations must embed UnimplementedCoordinationServiceServer
// for forward compatibility.
//
// CoordinationService is the control-plane gRPC API used by the NexusVPN
// client agent to register itself, discover peers on its networks, exchange
// ICE/NAT information for hole punching, and request relay allocation when
// direct peer-to-peer connectivity is not possible.
type CoordinationServiceServer interface {
	// RegisterDevice authenticates a device (via its device key + JWT) and
	// returns its assigned virtual IP and current network topology.
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	// Heartbeat reports liveness, NAT/endpoint info, and traffic counters.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// StreamPeerUpdates is a server-streaming RPC that pushes peer topology
	// changes (joins, leaves, endpoint changes) for all networks the device
	// belongs to, so the client can keep its local WireGuard peer table live.
	StreamPeerUpdates(*StreamPeerUpdatesRequest, grpc.ServerStreamingServer[PeerUpdate]) error
	// ExchangeICECandidates relays STUN-discovered candidate endpoints between
	// two peers to negotiate the best path (direct vs relay) for UDP hole punching.
	ExchangeICECandidates(context.Context, *ICEExchangeRequest) (*ICEExchangeResponse, error)
	// RequestRelay asks the control plane for the least-loaded relay server
	// to fall back to when direct P2P connectivity cannot be established.
	RequestRelay(context.Context, *RequestRelayRequest) (*RequestRelayResponse, error)
	mustEmbedUnimplementedCoordinationServiceServer()
}

// UnimplementedCoordinationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinationServiceServer struct{}

func (UnimplementedCoordinationServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedCoordinationServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCoordinationServiceServer) StreamPeerUpdates(*StreamPeerUpdatesRequest, grpc.ServerStreamingServer[PeerUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamPeerUpdates not implemented")
}
func (UnimplementedCoordinationServiceServer) ExchangeICECandidates(context.Context, *ICEExchangeRequest) (*ICEExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeICECandidates not implemented")
}
func (UnimplementedCoordinationServiceServer) RequestRelay(context.Context, *RequestRelayRequest) (*RequestRelayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestRelay not implemented")
}
func (UnimplementedCoordinationServiceServer) mustEmbedUnimplementedCoordinationServiceServer() {}
func (UnimplementedCoordinationServiceServer) testEmbeddedByValue()                             {}

// UnsafeCoordinationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinationServiceServer will
// result in compilation errors.
type UnsafeCoordinationServiceServer interface {
	mustEmbedUnimplementedCoordinationServiceServer()
}

func RegisterCoordinationServiceServer(s grpc.ServiceRegistrar, srv CoordinationServiceServer) {
	// If the following call panics, it indicates UnimplementedCoordinationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinationService_ServiceDesc, srv)
}

func _CoordinationService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_StreamPeerUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPeerUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinationServiceServer).StreamPeerUpdates(m, &grpc.GenericServerStream[StreamPeerUpdatesRequest, PeerUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinationService_StreamPeerUpdatesServer = grpc.ServerStreamingServer[PeerUpdate]

func _CoordinationService_ExchangeICECandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ICEExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).ExchangeICECandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_ExchangeICECandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).ExchangeICECandidates(ctx, req.(*ICEExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_RequestRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).RequestRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationService_RequestRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).RequestRelay(ctx, req.(*RequestRelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinationService_ServiceDesc is the grpc.ServiceDesc for CoordinationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexusvpn.coordination.v1.CoordinationService",
	HandlerType: (*CoordinationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _CoordinationService_RegisterDevice_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CoordinationService_Heartbeat_Handler,
		},
		{
			MethodName: "ExchangeICECandidates",
			Handler:    _CoordinationService_ExchangeICECandidates_Handler,
		},
		{
			MethodName: "RequestRelay",
			Handler:    _CoordinationService_RequestRelay_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPeerUpdates",
			Handler:       _CoordinationService_StreamPeerUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "coordination/v1/coordination.proto",
}
