// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {main} from '../models';

export function Connect(arg1:string):Promise<void>;

export function CreateNetwork(arg1:string,arg2:string,arg3:string):Promise<agent.Network>;

export function Disconnect():Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetSession():Promise<agent.Session>;

export function GetStatus():Promise<agent.Status>;

export function JoinNetwork(arg1:string):Promise<agent.Network>;

export function ListNetworks():Promise<Array<agent.Network>>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Logout():Promise<void>;

export function RotateDeviceKey():Promise<string>;

export function SetDeviceName(arg1:string):Promise<void>;
