// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNetwork'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetLocalServer() {
  return window['go']['main']['App']['GetLocalServer']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function GetStartWithSystem() {
  return window['go']['main']['App']['GetStartWithSystem']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InviteLink(arg1) {
  return window['go']['main']['App']['InviteLink'](arg1);
}

export function JoinNetwork(arg1) {
  return window['go']['main']['App']['JoinNetwork'](arg1);
}

export function ListNetworks() {
  return window['go']['main']['App']['ListNetworks']();
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function RotateDeviceKey() {
  return window['go']['main']['App']['RotateDeviceKey']();
}

export function SetDeviceName(arg1) {
  return window['go']['main']['App']['SetDeviceName'](arg1);
}

export function SetReachableFromAnywhere(arg1) {
  return window['go']['main']['App']['SetReachableFromAnywhere'](arg1);
}

export function SetRelayHere(arg1) {
  return window['go']['main']['App']['SetRelayHere'](arg1);
}

export function SetServerRole(arg1) {
  return window['go']['main']['App']['SetServerRole'](arg1);
}

export function SetStartWithSystem(arg1) {
  return window['go']['main']['App']['SetStartWithSystem'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartPairing(arg1) {
  return window['go']['main']['App']['StartPairing'](arg1);
}

export function StopUsingExitNode() {
  return window['go']['main']['App']['StopUsingExitNode']();
}

export function TakePendingInvite() {
  return window['go']['main']['App']['TakePendingInvite']();
}

export function UseExitNode(arg1, arg2) {
  return window['go']['main']['App']['UseExitNode'](arg1, arg2);
}
